// Auto-generated by the World Cup Bracket Predictor. Do not edit by hand.
const predictions = [
  {
    "name": "TEST - delete me",
    "date": "2026-06-25T09:20:42.512Z",
    "goldenBoot": "Test Player",
    "goldenBall": "Test Player",
    "predictions": [
      "Game1: AWB"
    ]
  },
  {
    "name": "Tony Tony",
    "date": "2026-06-25T09:30:30.506Z",
    "goldenBoot": "Harry Kane",
    "goldenBall": "Messi",
    "predictions": [
      "Game1: ArgentinaWAustralia",
      "Game2: BrazilWCanada",
      "Game3: FranceWCroatia",
      "Game4: EnglandWDenmark",
      "Game5: SpainWEcuador",
      "Game6: GhanaWGermany",
      "Game7: IranWPortugal",
      "Game8: JapanWNetherlands",
      "Game9: BelgiumWMexico",
      "Game10: MoroccoWItaly",
      "Game11: UruguayWNigeria",
      "Game12: ColombiaWPoland",
      "Game13: USAWQatar",
      "Game14: SwitzerlandWSenegal",
      "Game15: Mexico IIWSerbia",
      "Game16: Denmark IIWSouth Korea",
      "Game17: BrazilWArgentina",
      "Game18: EnglandWFrance",
      "Game19: SpainWGhana",
      "Game20: IranWJapan",
      "Game21: BelgiumWMorocco",
      "Game22: UruguayWColombia",
      "Game23: USAWSwitzerland",
      "Game24: Mexico IIWDenmark II",
      "Game25: EnglandWBrazil",
      "Game26: SpainWIran",
      "Game27: BelgiumWUruguay",
      "Game28: USAWMexico II",
      "Game29: EnglandWSpain",
      "Game30: USAWBelgium",
      "Game31: USAWEngland"
    ]
  },
  {
    "name": "Jimmy hhgd",
    "date": "2026-06-25T09:45:33.449Z",
    "goldenBoot": "Messi",
    "goldenBall": "Bob",
    "predictions": [
      {
        "game": "Game1",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "ArgentinaWAustralia"
      },
      {
        "game": "Game2",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "CanadaWBrazil"
      },
      {
        "game": "Game3",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "CroatiaWFrance"
      },
      {
        "game": "Game4",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "DenmarkWEngland"
      },
      {
        "game": "Game5",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "SpainWEcuador"
      },
      {
        "game": "Game6",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "GermanyWGhana"
      },
      {
        "game": "Game7",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "IranWPortugal"
      },
      {
        "game": "Game8",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "JapanWNetherlands"
      },
      {
        "game": "Game9",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "MexicoWBelgium"
      },
      {
        "game": "Game10",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "ItalyWMorocco"
      },
      {
        "game": "Game11",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "UruguayWNigeria"
      },
      {
        "game": "Game12",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "PolandWColombia"
      },
      {
        "game": "Game13",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "QatarWUSA"
      },
      {
        "game": "Game14",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "SenegalWSwitzerland"
      },
      {
        "game": "Game15",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "SerbiaWMexico II"
      },
      {
        "game": "Game16",
        "stage": "Round of 32",
        "points": 1,
        "prediction": "South KoreaWDenmark II"
      },
      {
        "game": "Game17",
        "stage": "Round of 16",
        "points": 2,
        "prediction": "ArgentinaWCanada"
      },
      {
        "game": "Game18",
        "stage": "Round of 16",
        "points": 2,
        "prediction": "DenmarkWCroatia"
      },
      {
        "game": "Game19",
        "stage": "Round of 16",
        "points": 2,
        "prediction": "GermanyWSpain"
      },
      {
        "game": "Game20",
        "stage": "Round of 16",
        "points": 2,
        "prediction": "JapanWIran"
      },
      {
        "game": "Game21",
        "stage": "Round of 16",
        "points": 2,
        "prediction": "ItalyWMexico"
      },
      {
        "game": "Game22",
        "stage": "Round of 16",
        "points": 2,
        "prediction": "UruguayWPoland"
      },
      {
        "game": "Game23",
        "stage": "Round of 16",
        "points": 2,
        "prediction": "QatarWSenegal"
      },
      {
        "game": "Game24",
        "stage": "Round of 16",
        "points": 2,
        "prediction": "South KoreaWSerbia"
      },
      {
        "game": "Game25",
        "stage": "Quarterfinals",
        "points": 4,
        "prediction": "ArgentinaWDenmark"
      },
      {
        "game": "Game26",
        "stage": "Quarterfinals",
        "points": 4,
        "prediction": "JapanWGermany"
      },
      {
        "game": "Game27",
        "stage": "Quarterfinals",
        "points": 4,
        "prediction": "ItalyWUruguay"
      },
      {
        "game": "Game28",
        "stage": "Quarterfinals",
        "points": 4,
        "prediction": "South KoreaWQatar"
      },
      {
        "game": "Game29",
        "stage": "Semifinals",
        "points": 8,
        "prediction": "ArgentinaWJapan"
      },
      {
        "game": "Game30",
        "stage": "Semifinals",
        "points": 8,
        "prediction": "ItalyWSouth Korea"
      },
      {
        "game": "Game31",
        "stage": "Final",
        "points": 16,
        "prediction": "ItalyWArgentina"
      }
    ]
  }
];
